# Generated by Django 6.0.3 on 2026-05-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('prompt_count', models.IntegerField(default=0)),
                ('last_generation', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guest Usage',
                'verbose_name_plural': 'Guest Usages',
                'unique_together': {('session_id', 'ip_address')},
            },
        ),
    ]
