# Generated by Django 6.0.3 on 2026-05-10 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptapp', '0003_prompt_tags_prompt_view_count_comment_notification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='promptapp.comment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('LIKE', 'liked your prompt'), ('COMMENT', 'commented on your prompt'), ('REPLY', 'replied to your comment'), ('MENTION', 'mentioned you in a comment'), ('SYSTEM', 'System notification')], max_length=10),
        ),
    ]
