# Generated by Django 6.0.3 on 2026-05-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptapp', '0004_alter_comment_options_comment_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('LIKE', 'liked your prompt'), ('DISLIKE', 'disliked your prompt'), ('COMMENT', 'commented on your prompt'), ('REPLY', 'replied to your comment'), ('MENTION', 'mentioned you in a comment'), ('SYSTEM', 'System notification')], max_length=10),
        ),
    ]
