# Generated by Django 6.0.3 on 2026-05-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptapp', '0007_alter_notification_type_aiimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiimage',
            name='inspired_by',
            field=models.CharField(blank=True, help_text='Manual creator mentions or external links', max_length=255),
        ),
    ]
