# Generated by Django 6.0.3 on 2026-05-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptapp', '0008_aiimage_inspired_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_prompts/%Y/%m/%d/'),
        ),
    ]
